<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Microsoft.AspNet.Web.Optimization.WebForms</RootNamespace>
    <Description>Web Forms controls for Rehost.Web optimization bundles.</Description>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Microsoft.AspNet.Web.Optimization.WebForms.ReferenceSource/**/*.cs" />
    <Compile Remove="../Microsoft.AspNet.Web.Optimization.WebForms.ReferenceSource/Properties/AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Rehost.Web.Optimization/Rehost.Web.Optimization.csproj" />
    <ProjectReference Include="../Rehost.Web.Package/Rehost.Web.Package.csproj" />
    <ProjectReference Include="../Rehost.Web/Rehost.Web.csproj" PrivateAssets="all" />
  </ItemGroup>
</Project>
