<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Sidecar.props" />
  <PropertyGroup>
    <AssemblyName>YAF.Lucene.Net</AssemblyName>
    <RootNamespace>YAF.Lucene.Net</RootNamespace>
    <Source>$(YafSrc)Lucene.Net/Lucene.Net/</Source>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(Source)**/*.cs" Exclude="$(Source)Index/Memory/**" Link="%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="J2N" Version="2.2.0-alpha-0048" />
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="10.0.11" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>
</Project>
