<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Sidecar.props" />
  <PropertyGroup>
    <AssemblyName>YAF.UrlRewriter</AssemblyName>
    <RootNamespace>YAF.UrlRewriter</RootNamespace>
    <Source>$(YafSrc)YAF.UrlRewriter/</Source>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(Source)**/*.cs" Link="%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="$(Source)Messages.resx" Link="Messages.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Rehost.WebForms" Version="$(RehostWebFormsVersion)" />
    <ProjectReference Include="../YAF.Configuration/YAF.Configuration.csproj" />
    <ProjectReference Include="../YAF.Types/YAF.Types.csproj" />
  </ItemGroup>
</Project>
