<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FrameworkOracle.Runner</AssemblyName>
    <RootNamespace>FrameworkOracle.Runner</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../FrameworkOracle.Contracts/FrameworkOracle.Contracts.csproj" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>
