using System.Diagnostics.Tracing;
using Rehost.WebForms.Hosting;
using Shouldly;
using Xunit;

namespace Rehost.WebForms.Runtime.Tests.Hosting;

// Framework raises nothing here. The port reports because its auto-generated keys are per-process
// (ledger P15), so a restart silently invalidates every payload protected with them.
[Collection(nameof(ApplicationBootstrapCollection))]
public sealed class AutoGeneratedMachineKeyReportTests
{
    [Fact]
    public void Reports_The_Shipped_Default_Which_Auto_Generates_Both_Keys()
    {
        using var application = TemporaryApplication.Create();
        using var listener = new RuntimeEventCollector();

        ApplicationConfigurationPreflight.Validate(application.CreateConfiguration());

        listener.Payloads.ShouldContain("validationKey and decryptionKey");
    }

    [Fact]
    public void Reports_Only_The_Key_That_Is_Auto_Generated()
    {
        using var application = TemporaryApplication.Create();
        WriteMachineKey(
            application,
            "validationKey=\"AutoGenerate\" decryptionKey=\"5D96763F754B1A37C60A65B3B47C54684BDFE91CB5F56870021D5DA0477F6C3A\"");
        using var listener = new RuntimeEventCollector();

        ApplicationConfigurationPreflight.Validate(application.CreateConfiguration());

        listener.Payloads.ShouldContain("validationKey");
        listener.Payloads.ShouldNotContain("validationKey and decryptionKey");
    }

    // The suffix is part of the shipped default, so a key that carries it is still explicit.
    [Fact]
    public void Stays_Silent_When_Both_Keys_Are_Explicit()
    {
        using var application = TemporaryApplication.Create();
        WriteMachineKey(
            application,
            "validationKey=\"E5E96E17E2FC4E4F325AD4B9374112BC5298EA7F6833E5EB2829FA61DEA8ABC7DBF63EDD75EE4A5B5B8E14A71B0F9E375BB35059AD8F42F314B48F1AB9AD337B,IsolateApps\" "
                + "decryptionKey=\"5D96763F754B1A37C60A65B3B47C54684BDFE91CB5F56870021D5DA0477F6C3A\"");
        using var listener = new RuntimeEventCollector();

        ApplicationConfigurationPreflight.Validate(application.CreateConfiguration());

        listener.Payloads.ShouldBeEmpty();
    }

    private static void WriteMachineKey(TemporaryApplication application, string attributes)
    {
        File.WriteAllText(
            Path.Combine(application.PhysicalRoot.FullName, "web.config"),
            $"""
            <configuration>
              <system.web>
                <machineKey {attributes} validation="HMACSHA256" decryption="AES" />
              </system.web>
            </configuration>
            """);
    }

    private sealed class RuntimeEventCollector : EventListener
    {
        private readonly List<string> _payloads = [];

        internal IReadOnlyList<string> Payloads
        {
            get
            {
                lock (_payloads)
                {
                    return _payloads.ToArray();
                }
            }
        }

        protected override void OnEventSourceCreated(EventSource eventSource)
        {
            if (eventSource.Name == "Rehost.WebForms.Runtime")
            {
                EnableEvents(eventSource, EventLevel.Warning);
            }
        }

        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            if (eventData.EventId != 7)
            {
                return;
            }

            lock (_payloads)
            {
                _payloads.Add(eventData.Payload?[0] as string ?? "");
            }
        }
    }
}
