<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Sidecar.props" />
  <PropertyGroup>
    <AssemblyName>System.Web.Http.WebHost</AssemblyName>
    <RootNamespace>System.Web.Http.WebHost</RootNamespace>
    <DefineConstants>$(DefineConstants);ASPNETMVC</DefineConstants>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.cs" Exclude="bin/**;obj/**" />
    <EmbeddedResource Include="Common/CommonWebApiResources.resx" LogicalName="System.Web.Http.WebHost.Properties.CommonWebApiResources.resources" />
    <EmbeddedResource Include="Properties/SRResources.resx" LogicalName="System.Web.Http.WebHost.Properties.SRResources.resources" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Rehost.WebForms" Version="$(RehostWebFormsVersion)" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
  </ItemGroup>
</Project>
