<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>CoreParity.Contracts</AssemblyName>
    <RootNamespace>CoreParity.Contracts</RootNamespace>
  </PropertyGroup>
</Project>
