<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>Rehost.WebForms.WebServices</AssemblyName>
    <RootNamespace>System.Web.Services</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../System.Web.Services.ReferenceSource/System/Web/Services/WsiProfiles.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Rehost.WebForms.Runtime/Rehost.WebForms.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.Security.Permissions" />
  </ItemGroup>
</Project>
