<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rehost.WebForms.ScriptManager.Bundles</RootNamespace>
    <Description>Stock Web Forms ScriptManager mappings for Rehost.WebForms.</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Rehost.WebForms/Rehost.WebForms.csproj" />
    <ProjectReference Include="../Rehost.WebForms.Extensions/Rehost.WebForms.Extensions.csproj" PrivateAssets="all" />
    <ProjectReference Include="../Rehost.WebForms.Runtime/Rehost.WebForms.Runtime.csproj" PrivateAssets="all" />
  </ItemGroup>
</Project>
