<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Rehost.Web.WebPages.Deployment/Rehost.Web.WebPages.Deployment.csproj" />
    <ProjectReference Include="../../src/Rehost.Web/Rehost.Web.csproj" />
  </ItemGroup>

</Project>
