namespace Rehost.Web.Hosting;

using System;
using System.IO;
using System.Security.Cryptography;
using System.Web.Configuration;

// Keyed on the application directory rather than the host application ID, matching
// CodegenDirectory, so renaming the host label keeps the previous keys (ADR 0010).
internal static class AutogenKeyStore
{
    // Must equal HttpRuntime.s_autogenKeys.Length: SetAutogenKeys block-copies the whole file
    // into that buffer.
    internal const int KeyFileLength = 1024;

    internal const string KeyFileExtension = ".autogen-keys";

    internal const string HostSource = "the host MachineKeyDirectory option";

    internal const string DefaultSource = "the default per-user key directory";

    internal static string DefaultDirectory
    {
        get
        {
            var profile = UserProfileDirectory.Resolve();
            if (profile == null)
            {
                throw new InvalidOperationException(
                    "Auto-generated machine keys persist under the user profile, but no user " +
                    "profile directory is available. Set the host MachineKeyDirectory option.");
            }

            return Path.Combine(profile, UserProfileDirectory.FolderName, "machine-keys");
        }
    }

    internal static string ResolveKeyFilePath(
        ApplicationBootstrapConfiguration configuration,
        out string source)
    {
        var directory = configuration.MachineKeyDirectory;
        source = directory != null ? HostSource : DefaultSource;
        return Path.Combine(
            directory ?? DefaultDirectory,
            FileSegment(configuration.PhysicalRootPath) + KeyFileExtension);
    }

    internal static string FileSegment(string physicalApplicationRoot) =>
        ApplicationPathDigest.Segment(physicalApplicationRoot, byteCount: 16);

    internal static byte[] TryGetPersistedKeys()
    {
        var configuration = RehostWebApplication.InitializedOrNull;
        if (configuration == null)
        {
            return null;
        }

        var machineKey = RuntimeConfig.GetAppConfig().MachineKey;
        if (!MachineKeyEnvironmentOverrides.IsAutoGenerated(
                MachineKeyEnvironmentOverrides.EffectiveValidationKey(machineKey)) &&
            !MachineKeyEnvironmentOverrides.IsAutoGenerated(
                MachineKeyEnvironmentOverrides.EffectiveDecryptionKey(machineKey)))
        {
            return null;
        }

        return LoadOrCreate(configuration);
    }

    internal static byte[] LoadOrCreate(ApplicationBootstrapConfiguration configuration)
    {
        var path = ResolveKeyFilePath(configuration, out var source);
        var existing = TryReadKeyFile(path, source);
        if (existing != null)
        {
            return existing;
        }

        EnsureDirectory(Path.GetDirectoryName(path), source);
        PublishFreshKeys(path, source);

        return TryReadKeyFile(path, source) ?? throw new InvalidOperationException(
            $"The machine-key file '{path}' disappeared while being created. " +
            $"Its directory comes from {source}.");
    }

    private static void EnsureDirectory(string directory, string source)
    {
        try
        {
            if (Directory.Exists(directory))
            {
                return;
            }

            Directory.CreateDirectory(directory);
            if (!OperatingSystem.IsWindows())
            {
                File.SetUnixFileMode(
                    directory,
                    UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute);
            }
        }
        catch (Exception exception) when (
            exception is IOException ||
            exception is UnauthorizedAccessException)
        {
            throw new InvalidOperationException(
                $"The machine-key directory '{directory}' cannot be created. " +
                $"It comes from {source}.",
                exception);
        }
    }

    private static void PublishFreshKeys(string path, string source)
    {
        var temporary = $"{path}.{Guid.NewGuid():n}.tmp";
        try
        {
            var options = new FileStreamOptions
            {
                Mode = FileMode.CreateNew,
                Access = FileAccess.Write,
                Share = FileShare.None,
            };
            if (!OperatingSystem.IsWindows())
            {
                options.UnixCreateMode = UnixFileMode.UserRead | UnixFileMode.UserWrite;
            }

            using (var stream = new FileStream(temporary, options))
            {
                stream.Write(RandomNumberGenerator.GetBytes(KeyFileLength));
            }

            File.Move(temporary, path, overwrite: false);
        }
        catch (IOException) when (File.Exists(path))
        {
            // Lost the creation race. The winner's file is complete because Move publishes it
            // atomically, so the caller re-reads instead of failing.
        }
        catch (Exception exception) when (
            exception is IOException ||
            exception is UnauthorizedAccessException)
        {
            throw new InvalidOperationException(
                $"The machine-key file '{path}' cannot be created. " +
                $"Its directory comes from {source}.",
                exception);
        }
        finally
        {
            try
            {
                File.Delete(temporary);
            }
            catch (Exception exception) when (
                exception is IOException ||
                exception is UnauthorizedAccessException)
            {
            }
        }
    }

    private static byte[] TryReadKeyFile(string path, string source)
    {
        byte[] content;
        try
        {
            content = File.ReadAllBytes(path);
        }
        catch (FileNotFoundException)
        {
            return null;
        }
        catch (DirectoryNotFoundException)
        {
            return null;
        }
        catch (Exception exception) when (
            exception is IOException ||
            exception is UnauthorizedAccessException)
        {
            throw new InvalidOperationException(
                $"The machine-key file '{path}' cannot be read. Its directory comes from {source}.",
                exception);
        }

        if (content.Length != KeyFileLength)
        {
            throw new InvalidOperationException(
                $"The machine-key file '{path}' is {content.Length} bytes; expected " +
                $"{KeyFileLength}. Delete the file to generate new keys; payloads protected " +
                $"with the old keys become invalid. Its directory comes from {source}.");
        }

        return content;
    }
}
