<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Microsoft.Web.Infrastructure</RootNamespace>
    <Description>Microsoft.Web.Infrastructure API for Rehost.Web.</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="../Rehost.Web.Package/Rehost.Web.Dependencies.props" />

  <ItemGroup>
    <ProjectReference Include="../Rehost.Web/Rehost.Web.csproj" />
  </ItemGroup>
</Project>
