namespace System.Web.Configuration;

using System;
using System.Configuration;
using Rehost.Web.Hosting;

internal static class MachineKeyEnvironmentOverrides
{
    internal const string ValidationKeyVariable =
        RehostWebOptions.MachineKeyValidationKeyVariable;
    internal const string DecryptionKeyVariable =
        RehostWebOptions.MachineKeyDecryptionKeyVariable;

    internal static string EffectiveValidationKey(MachineKeySection section)
    {
        return Apply(
            section.ValidationKey,
            RehostWebApplication.InitializedOrNull?.MachineKeyValidationKeyOverride,
            "validationKey",
            ValidationKeyVariable);
    }

    internal static string EffectiveDecryptionKey(MachineKeySection section)
    {
        return Apply(
            section.DecryptionKey,
            RehostWebApplication.InitializedOrNull?.MachineKeyDecryptionKeyOverride,
            "decryptionKey",
            DecryptionKeyVariable);
    }

    internal static string Apply(
        string declared,
        string supplied,
        string attributeName,
        string variableName)
    {
        if (String.IsNullOrWhiteSpace(supplied))
        {
            return declared;
        }

        if (!IsAutoGenerated(declared))
        {
            throw new ConfigurationErrorsException(
                $"machineKey {attributeName} is declared explicitly in configuration and is also " +
                $"supplied by the {variableName} environment variable. Remove one of the two.");
        }

        return supplied;
    }

    internal static bool IsAutoGenerated(string key)
    {
        return key != null && key.Contains("AutoGenerate", StringComparison.Ordinal);
    }
}
