<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>MyApp</AssemblyName>
    <RootNamespace>MyApp</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RehostAppContentRoot>../WEBAPP_PATH/</RehostAppContentRoot>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rehost.WebForms" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.WebForms.FriendlyUrls" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.WebForms.Optimization" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.WebForms.Optimization.WebForms" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.WebForms.ScriptManager.Bundles" Version="REHOST_VERSION" />
  </ItemGroup>
</Project>
