<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>System.Web</AssemblyName>
    <RootNamespace>System.Web</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../System.Web.ReferenceSource/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Rehost.WebForms.ApplicationServices/Rehost.WebForms.ApplicationServices.csproj" />
    <ProjectReference Include="../../eng/Rehost.WebForms.ReferenceSource.BuildInputs/Rehost.WebForms.ReferenceSource.BuildInputs.csproj"
                      Private="false"
                      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="System.CodeDom" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.Data.SqlClient" />
    <PackageReference Include="System.DirectoryServices" />
    <PackageReference Include="System.DirectoryServices.Protocols" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Runtime.Caching" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
    <PackageReference Include="System.Security.Permissions" />
  </ItemGroup>

  <Import Project="../../eng/Rehost.WebForms.GeneratedInputs/Rehost.WebForms.GeneratedInputs.targets" />
</Project>
