namespace System.Web.Util {
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.Tracing;

    internal enum AssemblyResolutionOutcome {
        Compiled,
        Loaded,
        Absent,
    }

    // Portable replacement for the native ASP.NET event-log reporter in webengine4.dll.
    // Callers keep their original sequence; only the platform operation differs.
    // Reporting must never fail the request being reported on, so the whole wrapper body is
    // swallowed — stringification and log providers can both throw.
    [EventSource(Name = WebFormsRuntimeLogger.Category)]
    internal sealed class WebFormsRuntimeEventSource : EventSource {
        internal static readonly WebFormsRuntimeEventSource Log = new WebFormsRuntimeEventSource();

        private WebFormsRuntimeEventSource() {
        }

        [NonEvent]
        private static void Swallow(Action report) {
            try {
                report();
            }
            catch {
            }
        }

        [NonEvent]
        internal void UnhandledException(Exception exception, string eventInfo) {
            Swallow(() => {
                WebFormsRuntimeLogger.Logger.UnhandledException(exception, eventInfo);
                if (IsEnabled()) {
                    UnhandledException(eventInfo);
                }
            });
        }

        [NonEvent]
        internal void SwallowedRequestException(string site, Exception swallowed, string context) {
            Swallow(() => {
                WebFormsRuntimeLogger.Logger.SwallowedRequestException(swallowed, site, context);
                if (IsEnabled()) {
                    SwallowedRequestException(site, swallowed.ToString(), context);
                }
            });
        }

        [NonEvent]
        internal void AssemblyResolution(AssemblyResolutionOutcome outcome, string assemblyName) {
            Swallow(() => {
                var text = OutcomeText(outcome);
                WebFormsRuntimeLogger.Logger.AssemblyResolution(text, assemblyName);
                if (IsEnabled()) {
                    AssemblyResolution(text, assemblyName);
                }
            });
        }

        [NonEvent]
        internal void CompilationFailed(string outputAssembly, IEnumerable<string> diagnostics) {
            Swallow(() => {
                var text = String.Join(Environment.NewLine, diagnostics);
                WebFormsRuntimeLogger.Logger.CompilationFailed(outputAssembly, text);
                if (IsEnabled()) {
                    CompilationFailed(outputAssembly, text);
                }
            });
        }

        [NonEvent]
        internal void MonitorSampleFailed(string monitor, Exception exception) {
            Swallow(() => {
                WebFormsRuntimeLogger.Logger.MonitorSampleFailed(exception, monitor);
                if (IsEnabled()) {
                    MonitorSampleFailed(monitor, exception.ToString());
                }
            });
        }

        [NonEvent]
        internal void MonitorDisabled(string monitor, Exception exception) {
            Swallow(() => {
                WebFormsRuntimeLogger.Logger.MonitorDisabled(exception, monitor);
                if (IsEnabled()) {
                    MonitorDisabled(monitor, exception.ToString());
                }
            });
        }

        [NonEvent]
        internal void AutoGeneratedMachineKey(bool validationKey, bool decryptionKey, string keyFilePath) {
            Swallow(() => {
                var keys = validationKey && decryptionKey
                    ? "validationKey and decryptionKey"
                    : validationKey ? "validationKey" : "decryptionKey";
                WebFormsRuntimeLogger.Logger.AutoGeneratedMachineKey(keys, keyFilePath);
                if (IsEnabled()) {
                    AutoGeneratedMachineKey(keys, keyFilePath);
                }
            });
        }

        [NonEvent]
        internal void RuntimeError(Exception exception, object source) {
            Swallow(() => {
                var sourceName = source == null ? "(none)" : source.GetType().FullName;
                WebFormsRuntimeLogger.Logger.RuntimeError(exception, sourceName);
                if (IsEnabled()) {
                    RuntimeError(sourceName, exception.ToString());
                }
            });
        }

        [NonEvent]
        internal void RestartRequested(ApplicationShutdownReason reason) {
            Swallow(() => {
                var text = reason.ToString();
                WebFormsRuntimeLogger.Logger.RestartRequested(text);
                if (IsEnabled()) {
                    RestartRequested(text);
                }
            });
        }

        [Event(1, Level = EventLevel.Error, Message = "{0}")]
        private void UnhandledException(string eventInfo) {
            WriteEvent(1, eventInfo);
        }

        // .NET Framework discards these exceptions with no record of any kind; the port reports
        // them so that a failed request is diagnosable. The response is unaffected either way.
        [Event(2, Level = EventLevel.Error, Message = "{0} swallowed an exception; {2}: {1}")]
        private void SwallowedRequestException(string site, string exception, string context) {
            WriteEvent(2, site, exception, context);
        }

        [Event(3, Level = EventLevel.Verbose, Message = "Assembly {1} {0}")]
        private void AssemblyResolution(string outcome, string assemblyName) {
            WriteEvent(3, outcome, assemblyName);
        }

        [Event(4, Level = EventLevel.Error, Message = "Compilation of {0} failed: {1}")]
        private void CompilationFailed(string outputAssembly, string diagnostics) {
            WriteEvent(4, outputAssembly, diagnostics);
        }

        [Event(5, Level = EventLevel.Warning, Message = "{0} sampling failed: {1}")]
        private void MonitorSampleFailed(string monitor, string exception) {
            WriteEvent(5, monitor, exception);
        }

        [Event(6, Level = EventLevel.Error, Message = "{0} disabled after repeated failures: {1}")]
        private void MonitorDisabled(string monitor, string exception) {
            WriteEvent(6, monitor, exception);
        }

        [Event(7, Level = EventLevel.Warning, Message =
            "machineKey {0} auto-generated; keys persist in '{1}' and survive process restart " +
            "on this machine. Scale-out across machines requires an explicit <machineKey> or " +
            "the REHOST_WEBFORMS_MACHINEKEY_* environment variables.")]
        private void AutoGeneratedMachineKey(string keys, string keyFilePath) {
            WriteEvent(7, keys, keyFilePath);
        }

        [Event(8, Level = EventLevel.Error, Message = "Unhandled runtime error from {0}: {1}")]
        private void RuntimeError(string source, string exception) {
            WriteEvent(8, source, exception);
        }

        [Event(9, Level = EventLevel.Warning, Message =
            "The runtime asked for the application to be rebuilt ({0}).")]
        private void RestartRequested(string reason) {
            WriteEvent(9, reason);
        }

        [NonEvent]
        private static string OutcomeText(AssemblyResolutionOutcome outcome) {
            switch (outcome) {
                case AssemblyResolutionOutcome.Compiled:
                    return "compiled";
                case AssemblyResolutionOutcome.Loaded:
                    return "loaded";
                default:
                    return "absent";
            }
        }
    }
}
