#nullable enable

namespace System.Web.Util;

using System;
using System.Threading;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

internal static partial class WebFormsRuntimeLogger
{
    internal const string Category = "Rehost.WebForms.Runtime";

    private static ILogger _logger = NullLogger.Instance;

    internal static ILogger Logger => Volatile.Read(ref _logger);

    internal static void Publish(ILoggerFactory? loggerFactory)
    {
        Volatile.Write(
            ref _logger,
            loggerFactory == null ? NullLogger.Instance : loggerFactory.CreateLogger(Category));
    }

    internal static void ResetForTests()
    {
        Volatile.Write(ref _logger, NullLogger.Instance);
    }

    [LoggerMessage(EventId = 1, Level = LogLevel.Error, Message = "{eventInfo}")]
    internal static partial void UnhandledException(
        this ILogger logger,
        Exception exception,
        string eventInfo);

    [LoggerMessage(EventId = 2, Level = LogLevel.Warning, Message = "{site} swallowed an exception; {context}")]
    internal static partial void SwallowedException(
        this ILogger logger,
        Exception exception,
        string site,
        string context);

    [LoggerMessage(EventId = 3, Level = LogLevel.Debug, Message = "Assembly {assemblyName} {outcome}")]
    internal static partial void AssemblyResolution(
        this ILogger logger,
        string outcome,
        string assemblyName);

    [LoggerMessage(EventId = 4, Level = LogLevel.Error, Message = "Compilation of {outputAssembly} failed: {diagnostics}")]
    internal static partial void CompilationFailed(
        this ILogger logger,
        string outputAssembly,
        string diagnostics);

    [LoggerMessage(EventId = 5, Level = LogLevel.Warning, Message = "{monitor} sampling failed")]
    internal static partial void MonitorSampleFailed(
        this ILogger logger,
        Exception exception,
        string monitor);

    [LoggerMessage(EventId = 6, Level = LogLevel.Error, Message = "{monitor} disabled after repeated failures")]
    internal static partial void MonitorDisabled(
        this ILogger logger,
        Exception exception,
        string monitor);

    [LoggerMessage(EventId = 7, Level = LogLevel.Warning, Message =
        "machineKey {keys} auto-generated; keys persist in '{keyFilePath}' and survive process " +
        "restart on this machine. Scale-out across machines requires an explicit <machineKey> or " +
        "the REHOST_WEBFORMS_MACHINEKEY_* environment variables.")]
    internal static partial void AutoGeneratedMachineKey(
        this ILogger logger,
        string keys,
        string keyFilePath);

    [LoggerMessage(EventId = 10, Level = LogLevel.Error, Message =
        "<system.net> in {file} is not supported and declared for activation only; nothing on .NET " +
        "reads it. Configure proxies, connection limits and mail settings in code.")]
    internal static partial void SystemNetUnsupported(
        this ILogger logger,
        string file);

    [LoggerMessage(EventId = 11, Level = LogLevel.Warning, Message =
        "<system.webServer><caching> in {file}: profiles for {extensions} are ignored; IIS served " +
        "stored responses for them, this host runs every request.")]
    internal static partial void CachingProfilesIgnored(
        this ILogger logger,
        string file,
        string extensions);

    [LoggerMessage(EventId = 12, Level = LogLevel.Warning, Message =
        "<{element}> in {file} is not honored; {reason}")]
    internal static partial void SectionNotHonored(
        this ILogger logger,
        string file,
        string element,
        string reason);

    [LoggerMessage(EventId = 13, Level = LogLevel.Information, Message =
        "Rehost compilation temp path: {directory} ({source}).")]
    internal static partial void CompilationOutput(
        this ILogger logger,
        string directory,
        string source);

    [LoggerMessage(EventId = 14, Level = LogLevel.Warning, Message =
        "The compilation temporary directory '{directory}' from the {source} is inside the application " +
        "root; generated output there changes the application's own hash, so every restart " +
        "recompiles. Move it outside the application.")]
    internal static partial void CompilationOutputInsideApplication(
        this ILogger logger,
        string directory,
        string source);

    [LoggerMessage(EventId = 15, Level = LogLevel.Information, Message =
        "Rehost physical root path: {directory}")]
    internal static partial void PhysicalRoot(
        this ILogger logger,
        string directory);

    [LoggerMessage(EventId = 8, Level = LogLevel.Error, Message = "Unhandled runtime error from {source}")]
    internal static partial void RuntimeError(
        this ILogger logger,
        Exception exception,
        string source);

    [LoggerMessage(EventId = 9, Level = LogLevel.Warning, Message =
        "The runtime asked for the application to be rebuilt ({reason}).")]
    internal static partial void RestartRequested(this ILogger logger, string reason);
}
