<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>System.Web</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <NoWarn>$(NoWarn);CS0672;CS9191;SYSLIB0003;SYSLIB0051;CA1416</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <Import Project="../Rehost.WebForms/Rehost.WebForms.Dependencies.props" />

  <ItemGroup>
    <Compile
      Include="../System.Web.ApplicationServices.ReferenceSource/**/*.cs"
      Exclude="../System.Web.ApplicationServices.ReferenceSource/Hosting/CustomLoaderHelper.cs" />
    <EmbeddedResource
      Include="../System.Web.ApplicationServices.ReferenceSource/ApplicationServicesStrings.resx"
      LogicalName="System.Web.ApplicationServicesStrings.resources" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="../../eng/Rehost.WebForms.ReferenceSource.BuildInputs/Rehost.WebForms.ReferenceSource.BuildInputs.csproj"
      Private="false"
      PrivateAssets="all" />
  </ItemGroup>

</Project>
