<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../eng/Repo.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Rehost.WebForms.ScenarioProtocol/Rehost.WebForms.ScenarioProtocol.csproj" />
  </ItemGroup>
</Project>
