<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Sidecar.props" />
  <PropertyGroup>
    <AssemblyName>YAF.Lucene.Net.Analysis.Common</AssemblyName>
    <RootNamespace>YAF.Lucene.Net.Analysis.Common</RootNamespace>
    <Source>$(YafSrc)Lucene.Net/Lucene.Net.Analysis.Common/</Source>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(Source)**/*.cs" Link="%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="$(Source)**/*.rslp;$(Source)**/*.dtd;$(Source)**/*.txt" Link="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../YAF.Lucene.Net/YAF.Lucene.Net.csproj" />
  </ItemGroup>
</Project>
