<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Autofac.Integration.Web</AssemblyName>
    <RootNamespace>Autofac.Integration.Web</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS3001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rehost.Web" Version="$(RehostVersion)" />
    <PackageReference Include="Autofac" Version="4.9.1" />
  </ItemGroup>
</Project>
