//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    public partial class WapDemo
    {
        protected global::System.Web.UI.WebControls.TextBox Name;

        protected global::System.Web.UI.WebControls.Button Greet;

        protected global::System.Web.UI.WebControls.Label Answer;
    }
}
