<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>MyApp</AssemblyName>
    <RootNamespace>MyApp</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RehostAppContentRoot>../WEBAPP_PATH/</RehostAppContentRoot>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(RehostAppContentRoot)**/*.cs" />
    <Compile Remove="$(RehostAppContentRoot)bin/**" />
    <Compile Remove="$(RehostAppContentRoot)obj/**" />
    <Compile Remove="$(RehostAppContentRoot)packages/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Rehost.Web" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.AspNet.FriendlyUrls" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.AspNet.Web.Optimization" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.AspNet.Web.Optimization.WebForms" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.AspNet.ScriptManager.MSAjax" Version="REHOST_VERSION" />
    <PackageReference Include="Rehost.AspNet.ScriptManager.WebForms" Version="REHOST_VERSION" />
  </ItemGroup>
</Project>
