<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Sidecar.props" />
  <PropertyGroup>
    <AssemblyName>YAF.Web</AssemblyName>
    <RootNamespace>YAF.Web</RootNamespace>
    <Source>$(YafSrc)YAF.Web/</Source>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(Source)**/*.cs" Link="%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="$(YafSrc)GlobalAssemblyInfo.cs" Link="Properties/GlobalAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Rehost.WebForms" Version="$(RehostWebFormsVersion)" />
    <PackageReference Include="OEmbed.Core" Version="2.0.7" />
    <ProjectReference Include="../YAF.Configuration/YAF.Configuration.csproj" />
    <ProjectReference Include="../YAF.Core/YAF.Core.csproj" />
    <ProjectReference Include="../YAF.Types/YAF.Types.csproj" />
    <ProjectReference Include="../YAF.UrlRewriter/YAF.UrlRewriter.csproj" />
  </ItemGroup>
</Project>
